skip empty rows & list id
X-Notes/X-Notes-Web pull request #130
Opened 2022-02-12 14:20 UTC by davydqq

2022-02-12 16:44 UTC, kanopa commented on Backend/WriteAPI/WriteContext/Repositories/Notes/NoteRepository.cs
> +                    var text = content as TextNote;
you can combine two if condition, listId will be some bigger, but its dont matter

2022-02-12 16:44 UTC, kanopa commented on Backend/WriteAPI/Common/DTO/Notes/FullNoteContent/TextNoteDTO.cs
> +            int listId,
Why listId is in constructor if is always 0?

2022-02-12 16:44 UTC, kanopa commented on Backend/WriteAPI/WriteContext/Repositories/Notes/NoteRepository.cs
> +            return await GetWithFilteredContent(notes, settings);
Just question, you need await here? Its will be working like in js if you add await when you call GetNotesByUserIdWithoutNote?

2022-02-12 22:07 UTC, davydqq commented on Backend/WriteAPI/WriteContext/Repositories/Notes/NoteRepository.cs
> +                    var text = content as TextNote;
Can`t, firstly, need a cast to TextNote.

2022-02-12 22:08 UTC, davydqq commented on Backend/WriteAPI/Common/DTO/Notes/FullNoteContent/TextNoteDTO.cs
> +            int listId,
No, check [Backend/WriteAPI/BI/Mapping/AppCustomMapper.cs](https://github.com/STORM-TEAM-DEV/Noots/pull/130/files#diff-a900e620ca0c49e3fb8b2c412fd8f69b1af78cb59bb2e8295d09ed7ed5b795e8)

2022-02-12 22:09 UTC, davydqq commented on Backend/WriteAPI/WriteContext/Repositories/Notes/NoteRepository.cs
> +            return await GetWithFilteredContent(notes, settings);
It's possible, but for what. There is no benefit or disadvantage to this.

2022-02-13 00:14 UTC, kanopa requested changes

2022-02-13 00:14 UTC, kanopa commented on Backend/WriteAPI/Common/DTO/Notes/FullNoteContent/TextNoteDTO.cs
> +            int listId,
Why you need map list?
Why just not make static field with setted value?
public static int ListId = 0

2022-02-13 00:14 UTC, kanopa commented on Backend/WriteAPI/WriteContext/Repositories/Notes/NoteRepository.cs
> +                    var text = content as TextNote;
What's stopping you from doing it?
if(content.ContentTypeId == ContentTypeENUM.Text && text.NoteTextTypeId == NoteTextTypeENUM.Numberlist)
                {
                    var text = content as TextNote;
                    text.ListId = listId;
                } else
                {
                    listId++;
                }

2022-02-13 00:14 UTC, kanopa commented on Backend/WriteAPI/WriteContext/Repositories/Notes/NoteRepository.cs
> +            return await GetWithFilteredContent(notes, settings);
Why write a word if you can not write it 🤔

2022-02-13 00:16 UTC, kanopa commented on Backend/WriteAPI/Common/DTO/Notes/FullNoteContent/TextNoteDTO.cs
> +            int listId,
and you added listId after optional parameters, its bad, because now if you need list id and dont need bool or hType you anyway must setting them

2022-02-13 18:00 UTC, merged