Feature/ws updates and note impovements
X-Notes/X-Notes-Web pull request #132
Opened 2022-02-14 16:05 UTC by davydqq

2022-02-15 20:45 UTC, kanopa requested changes

2022-02-15 20:45 UTC, kanopa commented on Backend/WriteAPI/Common/DatabaseModels/Models/Files/AppFileMetaData.cs
> +        public int SecondsDuration { set; get; }
Why SecondsDuration is not nullable like in Backend/WriteAPI/Common/DTO/Notes/FullNoteContent/AudioNoteDTO.cs
In all pr SecondsDuration somewhere nullable somewhere not

2022-02-15 20:45 UTC, kanopa commented on Backend/WriteAPI/WriteContext/Repositories/Notes/NoteRepository.cs
> +                var baseContent = contentLookUp[note.Id].Where(x => x.ContentTypeId != ContentTypeENUM.Text || (x.ContentTypeId == ContentTypeENUM.Text && (x as TextNote).Contents?.Count > 0));
maybe separate and make more human readable?

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/content/notes/audio.service.ts
> +          const resp = await this.apiNoteFilesService
fix lint issues please

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/content/notes/audio.service.ts
> +      imageBlob: null as Blob,
dont cast, you can create field imageBlob later

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/content/notes/audio.service.ts
> +    return [result.duration, result.imageBlob, metadata.format.duration];
result.duration always empty string its need here?

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/content/notes/audio.service.ts
> +        const result = await this.getMetadata(audio.audioPath);
better to desctructurize result and use variables separately, like  const [duration, blob, durationBlob] = function

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/content/notes/audio.service.ts
> +          audio.secondsDuration = resp.data.metaData?.secondsDuration;
naming of secont duration is bad, whats is mean? better be totalDuration all smth else

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/content/notes/full-note/content-editor-services/file-content/content-editor-audios.service.ts
> +        new AudioModel(x.name, x.pathNonPhotoContent, x.id, x.authorId, x.createdAt, null, null),
duration is optional, dont need pass null

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/content/notes/full-note/full-note-components/audio-note/audio-note.component.ts
> +  implements ParentInteraction, OnInit, OnDestroy {
please remove OnInit, OnDestroy

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/content/notes/full-note/models/file-note-metadata.ts
> +  imagePath?: string;
somewhere imagePath is nullable, somewhere not

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/content/notes/full-note/models/file-note.ts
> +  metaData: FileNoteMetaData;
in backend api you sometimes check on metadata is null, so its nullable or not?

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/content/notes/models/editor-models/audios-collection.ts
> +  pathToImage: string;
pathToImage sometimes is null

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/shared/custom-components/audio-controls/audio-controls.component.scss
> +  height: 54px;
why?

2022-02-15 20:45 UTC, kanopa commented on Client/src/app/shared/custom-components/audio-small/audio-small.component.ts
> +  ngOnInit() {}
useless onInit

2022-02-15 21:16 UTC, davydqq commented on Client/src/app/shared/custom-components/audio-controls/audio-controls.component.scss
> +  height: 54px;
You can find answer [here](https://developer.mozilla.org/en-US/docs/Web/CSS/height)

2022-02-16 14:54 UTC, davydqq commented on Backend/WriteAPI/Common/DatabaseModels/Models/Files/AppFileMetaData.cs
> +        public int SecondsDuration { set; get; }
Because it`s DTO, when the user firstly uploads audio, the audio doesn`t contain any metadata. MetaData update as soon as possible after storage saving in the second query.

2022-02-16 14:55 UTC, davydqq commented on Backend/WriteAPI/WriteContext/Repositories/Notes/NoteRepository.cs
> +                var baseContent = contentLookUp[note.Id].Where(x => x.ContentTypeId != ContentTypeENUM.Text || (x.ContentTypeId == ContentTypeENUM.Text && (x as TextNote).Contents?.Count > 0));
you are feel free fix it

2022-02-16 15:04 UTC, davydqq commented on Client/src/app/content/notes/full-note/models/file-note.ts
> +  metaData: FileNoteMetaData;
currently, metaData values can be only in audio, all others have null in metaData

2022-02-16 15:30 UTC, davydqq commented on Client/src/app/content/notes/full-note/models/file-note-metadata.ts
> +  imagePath?: string;
is can be nullable

2022-02-17 20:15 UTC, merged