Feature/inner folder and menu buttons improvements
X-Notes/X-Notes-Web pull request #137
Opened 2022-04-03 18:18 UTC by davydqq

2022-04-12 23:29 UTC, kanopa requested changes

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/folders/folder.service.ts
> +            this.loadAdditionInformation(ids);
resolve promise, if promise is rejected it will throw unhandled promise rejection
add or await or catch statment
await this.loadAdditionInformation(ids); or this.loadAdditionInformation(ids).catch((e) => console.log(e))

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/folders/folder/folder.component.ts
> +  nameChanged: Subject<string> = new Subject<string>();
really changed,  hahahah

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/folders/full-folder/full-folder.component.scss
> +    width: calc(100% - 200px);
try to use flex: 1 instead of width calculation

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/folders/full-folder/full-folder.component.scss
> +        width: 100%;
good, but add also padding: 0

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/folders/full-folder/full-folder.component.ts
> +            await this.apiFullFolder.addNotesToFolder(ids, this.folder.id).toPromise();
they must be done in sequence? if not add 
`await Promise.all([this.apiFullFolder.addNotesToFolder(ids, this.folder.id).toPromise(), this.ffnService.updateNotesLayout(this.folder.id);])`

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/folders/state/folders-state.ts
> +  static getAllSelectedFoldersCanEdit(state: FolderState): boolean {
bad naming, every return true or false, in my opinion canEditSelectedFolders is better

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/navigation/header-components/interaction-inner-folder/interaction-inner-folder.component.html
> +    *ngIf="(pService.isMenuActive$ | async) === (false)"
*ngIf="!(pService.isMenuActive$ | async)"

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/navigation/models/menu-Item.model.ts
> +  IsNeedEditRightsToSee: boolean;
what is mean?

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/navigation/services/dialogs-manage.service.ts
> +    this.validateIds(ids);
in validation method you dont need to check if ids is not undefined, you typed ids as string[], its mean ids always been defined
change typization or remove !ids

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/navigation/services/dialogs-manage.service.ts
> +    this.validateIds(ids);
and throw new Error()? maybe just return from method?

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/navigation/services/menu-buttons.service.ts
> +      IsNeedEditRightsToSee: true,
to remove duplication you can create method with this 3 fields and after destructurize it here
`
private yourVars(isVisiable = true, isOnlyForAuthor = true, IsNeedEditRightsToSee = true) => 
({ isVisiable, isOnlyForAuthor,  IsNeedEditRightsToSee}
`

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/navigation/services/permissions-buttons.service.ts
> +  get IsCanEditFullNote(): boolean {
two verbs in row, just canEditFullNote

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/notes/full-note/full-note.component.ts
> +            await this.store.dispatch(new LoadFullNote(this.id)).toPromise();
do they have to be done sequentially? if not just add Promise.all()

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/content/notes/models/small-note.model.ts
> +  isCanEdit: boolean;
two verbs again, just canEdit

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/shared/modal_components/lock/lock.component.scss
> +    padding-left: 6px;
redudant p tag scope

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/shared/modal_components/open-inner-side/open-inner-side.component.html
> +    [icon]="'icon-plus'"
just change to static `icon="icon-plus"`

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/shared/modal_components/open-inner-side/open-inner-side.component.html
> +          [translate]="'subMenu'"
lets add translate as static translate="subMenu"

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/shared/modal_components/open-inner-side/open-inner-side.component.html
> +              id="{{ item.id }}"
чето стремное, [id]="item.id"

2022-04-12 23:29 UTC, kanopa commented on Client/src/app/shared/modal_components/share/share.component.ts
> +    console.log('notes: ', this.notes);
log

2022-04-13 13:13 UTC, davydqq commented on Client/src/app/shared/modal_components/open-inner-side/open-inner-side.component.html
> +          [translate]="'subMenu'"
I won't do that. it works....

2022-04-13 13:14 UTC, davydqq commented on Client/src/app/content/notes/models/small-note.model.ts
> +  isCanEdit: boolean;
I won't do that. it works....

2022-04-13 13:14 UTC, davydqq commented on Client/src/app/content/navigation/services/permissions-buttons.service.ts
> +  get IsCanEditFullNote(): boolean {
I won't do that. it works....

2022-04-13 13:17 UTC, davydqq commented on Client/src/app/content/navigation/header-components/interaction-inner-folder/interaction-inner-folder.component.html
> +    *ngIf="(pService.isMenuActive$ | async) === (false)"
![image](https://user-images.githubusercontent.com/40700475/163188741-acabecc0-2f8c-4cbc-9d8e-e1a3e4856df2.png)

2022-04-13 13:17 UTC, davydqq commented on Client/src/app/content/navigation/header-components/interaction-inner-folder/interaction-inner-folder.component.html
> +    *ngIf="(pService.isMenuActive$ | async) === (false)"
????

2022-04-13 13:20 UTC, davydqq commented on Client/src/app/content/notes/full-note/full-note.component.ts
> +            await this.store.dispatch(new LoadFullNote(this.id)).toPromise();
sequentially...

2022-04-13 13:21 UTC, davydqq commented on Client/src/app/content/navigation/services/menu-buttons.service.ts
> +      IsNeedEditRightsToSee: true,
useless syntactic fucking garbage, I won't do it

2022-04-13 13:24 UTC, davydqq commented on Client/src/app/content/navigation/models/menu-Item.model.ts
> +  IsNeedEditRightsToSee: boolean;
isOnlyForAuthor = only author can see menu items
IsNeedEditRightsToSee = only users that can edit rights can see menu items

2022-04-13 13:29 UTC, davydqq commented on Client/src/app/content/folders/folder.service.ts
> +            this.loadAdditionInformation(ids);
in any case we will get a design error catch will not solve anything

2022-04-13 13:31 UTC, davydqq commented on Client/src/app/content/folders/state/folders-state.ts
> +  static getAllSelectedFoldersCanEdit(state: FolderState): boolean {
I'm not going to fix the subjective stuff never!

2022-04-13 13:32 UTC, davydqq commented on Client/src/app/content/navigation/services/dialogs-manage.service.ts
> +    this.validateIds(ids);
> in validation method you dont need to check if ids is not undefined, you typed ids as string[], its mean ids always been defined change typization or remove !ids

lol, I can pass null

2022-04-13 13:33 UTC, davydqq commented on Client/src/app/content/navigation/services/dialogs-manage.service.ts
> +    this.validateIds(ids);
> and throw new Error()? maybe just return from method?

the window should not open without an ids

2022-04-13 13:41 UTC, davydqq commented on Client/src/app/content/folders/full-folder/full-folder.component.ts
> +            await this.apiFullFolder.addNotesToFolder(ids, this.folder.id).toPromise();
sequence...

2022-04-14 01:56 UTC, kanopa commented on Client/src/app/content/navigation/header-components/interaction-inner-folder/interaction-inner-folder.component.html
> +    *ngIf="(pService.isMenuActive$ | async) === (false)"
ok

2022-04-14 01:59 UTC, kanopa commented on Client/src/app/content/navigation/services/dialogs-manage.service.ts
> +    this.validateIds(ids);
you cannot pass null! if you typing arg as string[] you awaiting only string[], if this method can accept undefined or null change typisation

2022-04-14 02:12 UTC, kanopa commented
не понимаю что вызывает такой хейт, просто жалею что посмотрел этот пулл, взял и ведро дерьма на меня вылил. При том что как бы все что было написано сделает проект только лучше

2022-04-14 02:16 UTC, kanopa commented
По некоторым ответам ты как будто пишешь код абы работало, ты ж свой проект делаешь, опять же не понимаю отношения такого

2022-04-15 21:28 UTC, merged